import { MenuItem, MenuCategory } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // --- BLACK COFFEE ---
  {
    id: 'coffee_espresso',
    nameKa: 'ესპრესო / Espresso',
    nameEn: 'Espresso',
    category: MenuCategory.CoffeeBlack,
    detailsKa: 'ორმაგი რიშოტი',
    detailsEn: 'Double ristretto',
    isWine: false,
    price: 7,
  },
  {
    id: 'coffee_americano',
    nameKa: 'ამერიკანო / Americano',
    nameEn: 'Americano',
    category: MenuCategory.CoffeeBlack,
    detailsKa: 'ესპრესო ცხელი წყლით',
    detailsEn: 'Espresso with hot water',
    isWine: false,
    price: 8,
  },
  {
    id: 'coffee_batch_brew',
    nameKa: 'ფილტრ ყავა / Batch Brew',
    nameEn: 'Batch Brew',
    category: MenuCategory.CoffeeBlack,
    detailsKa: 'Specially მარცვალი, იცვლება ყოველდღიურად',
    detailsEn: 'Specialty beans, rotates daily',
    isWine: false,
    price: 9,
  },
  {
    id: 'coffee_pour_over',
    nameKa: 'V60 / Pour Over',
    nameEn: 'Pour Over',
    category: MenuCategory.CoffeeBlack,
    detailsKa: 'ხელით ნაყენი, პრემიუმ მონოსორტი',
    detailsEn: 'Hand-brewed, premium single-origin',
    isWine: false,
    price: 12,
  },

  // --- WITH MILK ---
  {
    id: 'coffee_cappuccino',
    nameKa: 'კაპუჩინო / Cappuccino',
    nameEn: 'Cappuccino',
    category: MenuCategory.CoffeeMilk,
    detailsKa: 'ორმაგი ესპრესო და ჰაეროვანი რძის ქაფი',
    detailsEn: 'Silky microfoam over rich double espresso',
    isWine: false,
    price: 9,
  },
  {
    id: 'coffee_latte',
    nameKa: 'ლატე / Latte',
    nameEn: 'Latte',
    category: MenuCategory.CoffeeMilk,
    detailsKa: 'ესპრესო და რბილი რძის ქაფი',
    detailsEn: 'Espresso with steamed textured milk',
    isWine: false,
    price: 10,
  },
  {
    id: 'coffee_flat_white',
    nameKa: 'ფლეტ ვაიტი / Flat White',
    nameEn: 'Flat White',
    category: MenuCategory.CoffeeMilk,
    detailsKa: 'უფრო ინტენსიური ყავის გემოთი',
    detailsEn: 'Double shot espresso with flat silky milk',
    isWine: false,
    price: 11,
  },
  {
    id: 'coffee_cortado',
    nameKa: 'კორტადო / Cortado',
    nameEn: 'Cortado',
    category: MenuCategory.CoffeeMilk,
    detailsKa: 'თანაბარი ესპრესო და რძე',
    detailsEn: 'Equal parts of double espresso and steamed milk',
    isWine: false,
    price: 8,
  },

  // --- COLD & REFRESHING ---
  {
    id: 'coffee_iced_americano',
    nameKa: 'ცივი ამერიკანო / Iced Americano',
    nameEn: 'Iced Americano',
    category: MenuCategory.CoffeeCold,
    detailsKa: 'ესპრესო ყინულით და ცივი წყლით',
    detailsEn: 'Chilled espresso over cold water and ice',
    isWine: false,
    price: 9,
  },
  {
    id: 'coffee_iced_latte',
    nameKa: 'ცივი ლატე / Iced Latte',
    nameEn: 'Iced Latte',
    category: MenuCategory.CoffeeCold,
    detailsKa: 'რძე, ორმაგი ესპრესო და ყინული',
    detailsEn: 'Classic iced double espresso latte drink',
    isWine: false,
    price: 11,
  },
  {
    id: 'coffee_espresso_tonic',
    nameKa: 'ესპრესო ტონიკი / Espresso Tonic',
    nameEn: 'Espresso Tonic',
    category: MenuCategory.CoffeeCold,
    detailsKa: 'ესპრესო შოტი და გამაგრილებელი ტონიკი',
    detailsEn: 'Refreshing sparkling tonic with double espresso on ice',
    isWine: false,
    price: 13,
  },
  {
    id: 'coffee_cold_brew',
    nameKa: 'ბუმბერაზი / Cold Brew',
    nameEn: 'Cold Brew',
    category: MenuCategory.CoffeeCold,
    detailsKa: 'ცივად დაყენებული, 16 საათიანი ექსტრაქცია',
    detailsEn: 'Cold infused, 16 hours slow extraction',
    isWine: false,
    price: 11,
  },

  // --- COFFEE OPTIONS / ADDONS ---
  {
    id: 'coffee_addon_alt_milk',
    nameKa: 'ალტერნატიული რძე (ნუში / შვრია / ქოქოსი)',
    nameEn: 'Alternative Milk (Almond / Oat / Coconut)',
    category: MenuCategory.CoffeeAddons,
    detailsKa: 'ალტერნატიული რძე (ნუში / შვრია / ქოქოსი)',
    detailsEn: 'Non-dairy milk option choice upgrade',
    isWine: false,
    price: 3,
  },
  {
    id: 'coffee_addon_extra_shot',
    nameKa: 'დამატებითი ესპრესო შოტი (Extra Shot)',
    nameEn: 'Extra Espresso Shot',
    category: MenuCategory.CoffeeAddons,
    detailsKa: 'დამატებითი ესპრესო შოტი',
    detailsEn: 'Additional double shot espresso addition',
    isWine: false,
    price: 3,
  },

  // --- BREAKFAST & STARTERS ---
  {
    id: 'starter_truffle_omelette',
    nameKa: 'საფირმო ტრიუფელის ომლეტი',
    nameEn: 'Signature Truffle Omelette',
    category: MenuCategory.BreakfastStarters,
    detailsKa: '3 კვერცხი, ტრიუფელის პასტა 10გ, პარმეზანი 15გ, ნაღები 30მლ, კარაქი 15გ, ბაგეტი 50გ.',
    detailsEn: '3 eggs, truffle paste 10g, parmesan 15g, cream 30ml, butter 15g, baguette 50g.',
    isWine: false,
    price: 24,
  },
  {
    id: 'starter_burrata_berries',
    nameKa: 'ბურატა თბილი კენკრით',
    nameEn: 'Burrata with Warm Berries',
    category: MenuCategory.BreakfastStarters,
    detailsKa: 'ბურატა 125გ, კენკრის მიქსი 80გ, შაქარი 15გ, ფსტა 15გ, პიტნა 2გ.',
    detailsEn: 'Burrata 125g, mixed berries 80g, sugar 15g, pistachio 15g, mint 2g.',
    isWine: false,
    price: 34,
  },
  {
    id: 'starter_baked_camembert',
    nameKa: 'გამომცხვარი კამამბერი',
    nameEn: 'Baked Camembert',
    category: MenuCategory.BreakfastStarters,
    detailsKa: 'კამამბერი 125გ, ნიორი 5გ, თაფლი 20გ, როზმარინი 2გ, ბაგეტი 60გ.',
    detailsEn: 'Camembert 125g, garlic 5g, honey 20g, rosemary 2g, baguette 60g.',
    isWine: false,
    price: 36,
  },
  {
    id: 'starter_assorted_bruschetta',
    nameKa: 'ბრუსკეტების ასორტი',
    nameEn: 'Assorted Bruschetta',
    category: MenuCategory.BreakfastStarters,
    detailsKa: '3 ცალი (ორაგული/სტრაჩატელა; პროშუტო/ლეღვი; პესტო/ჩერი/მოცარელა).',
    detailsEn: '3 pieces (salmon/stracciatella; prosciutto/fig; pesto/cherry/mozzarella).',
    isWine: false,
    price: 29,
  },

  // --- SALADS ---
  {
    id: 'salad_green_stracciatella',
    nameKa: 'მწვანე სალათი სტრაჩატელათი',
    nameEn: 'Green Salad with Stracciatella',
    category: MenuCategory.Salads,
    detailsKa: 'სალათის მიქსი 70გ, კიტრი 60გ, სტრაჩატელა 60გ, პესტო 25გ, ლაიმი 7მლ.',
    detailsEn: 'Salad mix 70g, cucumber 60g, stracciatella 60g, pesto 25g, lime 7ml.',
    isWine: false,
    price: 28,
  },
  {
    id: 'salad_asian_shrimp',
    nameKa: 'აზიური სალათი კრევეტებით',
    nameEn: 'Asian Shrimp Salad',
    category: MenuCategory.Salads,
    detailsKa: 'ვეფხვისებრი კრევეტები 5 ცალი (~90გ), სალათის მიქსი 50გ, ჩერი 50გ, ხახვი 15გ, აზიური დრესინგი 30მლ.',
    detailsEn: 'Tiger shrimp 5 pcs (~90g), salad mix 50g, cherry tomatoes 50g, onion 15g, Asian dressing 30ml.',
    isWine: false,
    price: 38,
  },

  // --- SANDWICHES ---
  {
    id: 'sandwich_black_angus',
    nameKa: 'შავი ანგუსის სენდვიჩი',
    nameEn: 'Black Angus Sandwich',
    category: MenuCategory.Sandwiches,
    detailsKa: 'ბაგეტი 80გ, ანგუსის სუკი 90გ, მოცარელა 40გ, დიჟონის მდოგვი 15გ, რუკოლა 15გ.',
    detailsEn: 'Baguette 80g, Angus beef tenderloin 90g, mozzarella 40g, Dijon mustard 15g, arugula 15g.',
    isWine: false,
    price: 36,
  },
  {
    id: 'sandwich_classic_prosciutto',
    nameKa: 'კლასიკური პროშუტო სენდვიჩი',
    nameEn: 'Classic Prosciutto Sandwich',
    category: MenuCategory.Sandwiches,
    detailsKa: 'ბაგეტი 80გ, პროშუტო 50გ, მოცარელა 40გ, ჩერი 30გ, პესტო 20გ.',
    detailsEn: 'Baguette 80g, prosciutto 50g, mozzarella 40g, cherry tomatoes 30g, pesto 20g.',
    isWine: false,
    price: 28,
  },
  {
    id: 'sandwich_smoked_salmon',
    nameKa: 'შებოლილი ორაგულის სენდვიჩი',
    nameEn: 'Smoked Salmon Sandwich',
    category: MenuCategory.Sandwiches,
    detailsKa: 'ბაგეტი 80გ, შებოლილი ორაგული 60გ, კრემ-ყველი 40გ, კიტრი 30გ, კამა 3გ.',
    detailsEn: 'Baguette 80g, smoked salmon 60g, cream cheese 40g, cucumber 30g, dill 3g.',
    isWine: false,
    price: 32,
  },

  // --- WINE BITES & PLATTERS ---
  {
    id: 'platter_black_angus_tartare',
    nameKa: 'შავი ანგუსის ტარტარი',
    nameEn: 'Black Angus Tartare',
    category: MenuCategory.WineBitesPlatters,
    detailsKa: 'ანგუსის სუკი 120გ, კაპერსი 10გ, ხახვი 15გ, დიჟონი 10გ, კვერცხის გული 1ც, ტოსტები 40გ.',
    detailsEn: 'Angus tenderloin 120g, capers 10g, onion 15g, Dijon mustard 10g, 1 egg yolk, toast 40g.',
    isWine: false,
    price: 42,
  },
  {
    id: 'platter_salmon_sashimi',
    nameKa: 'ორაგულის საშიმი ლაიმით',
    nameEn: 'Salmon Sashimi with Lime',
    category: MenuCategory.WineBitesPlatters,
    detailsKa: 'შებოლილი ორაგული 100გ, ლაიმის წვენი 15მლ, ზეითუნის ზეთი 15მლ, კაპერსი 10გ.',
    detailsEn: 'Smoked salmon 100g, lime juice 15ml, olive oil 15ml, capers 10g.',
    isWine: false,
    price: 36,
  },
  {
    id: 'platter_baked_oysters',
    nameKa: 'გამომცხვარი ხამანწკები პარმეზანით (3 ცალი)',
    nameEn: 'Baked Oysters with Parmesan (3 pcs)',
    category: MenuCategory.WineBitesPlatters,
    detailsKa: 'ხამანწკა 3 ცალი, ნივრიანი კარაქი, პარმეზანი.',
    detailsEn: 'Oysters 3 pieces, garlic butter, parmesan.',
    isWine: false,
    price: 45,
  },
  {
    id: 'platter_seared_octopus',
    nameKa: 'შემწვარი რვაფეხა',
    nameEn: 'Seared Octopus',
    category: MenuCategory.WineBitesPlatters,
    detailsKa: 'რვაფეხას საცეცი, კარტოფილის მუსი.',
    detailsEn: 'Octopus tentacle, creamy potato mousse.',
    isWine: false,
    price: 58,
  },
  {
    id: 'platter_cheese_european',
    nameKa: 'ევროპული ყველის დაფა',
    nameEn: 'European Cheese Platter',
    category: MenuCategory.WineBitesPlatters,
    detailsKa: 'მოცარელა, ლურჯი ყველი, დავარგებული ქართული ყველი, თაფლი, ჩირეული, თხილის მიქსი.',
    detailsEn: 'Mozzarella, blue cheese, aged Georgian cheese, honey, dried fruits, nut mix.',
    isWine: false,
    price: 55,
  },
  {
    id: 'platter_meat_premium',
    nameKa: 'პრემიუმ ხორცის დაფა',
    nameEn: 'Premium Meat Platter',
    category: MenuCategory.WineBitesPlatters,
    detailsKa: 'პროშუტო, სალიამი, მწვანე ზეთისხილი, კორნიშონები.',
    detailsEn: 'Prosciutto, salami, green olives, cornichons.',
    isWine: false,
    price: 58,
  },

  // --- DESSERTS ---
  {
    id: 'dessert_san_sebastian',
    nameKa: 'სან-სებასტიანი',
    nameEn: 'San Sebastian',
    category: MenuCategory.Desserts,
    detailsKa: 'კრემ-ყველი 160გ, ნაღები 90მლ, შაქარი 40გ, კვერცხი 1.5ც, კენკრის სოუსი 40გ.',
    detailsEn: 'Cream cheese 160g, cream 90ml, sugar 40g, 1.5 eggs, berry sauce 40g.',
    isWine: false,
    price: 18,
  },
  {
    id: 'dessert_brownie_sea_salt',
    nameKa: 'ბრაუნი ზღვის მარილით',
    nameEn: 'Brownie with Sea Salt',
    category: MenuCategory.Desserts,
    detailsKa: 'შოკოლადი+კარაქი 70გ, შაქარი 30გ, კვერცხი 1ც, ფქვილი 20გ, ფსტა/ნუში 10გ, მალდონის მარილი 1გ.',
    detailsEn: 'Chocolate+butter 70g, sugar 30g, 1 egg, flour 20g, pistachio/almond 10g, Maldon sea salt 1g.',
    isWine: false,
    price: 16,
  },

  // --- WHITE WINE (Classic) ---
  {
    id: 'wine_white_chiche_tsinandali',
    nameKa: 'Chiche • წინანდალი (2024)',
    nameEn: 'Chiche • Tsinandali (2024)',
    category: MenuCategory.WineClassicWhite,
    isWine: true,
    glassPrice: 13,
    bottlePrice: 54,
  },
  {
    id: 'wine_white_damilie_kissi',
    nameKa: 'Damilie • მადრასაული ქისი (2025)',
    nameEn: 'Damilie • Madrasauli Kisi (2025)',
    category: MenuCategory.WineClassicWhite,
    isWine: true,
    glassPrice: 18,
    bottlePrice: 78,
  },
  {
    id: 'wine_white_p_winery_khikhvi_classic',
    nameKa: 'პირველი მეღვინეობა • ხიხვი კლასიკი',
    nameEn: 'First Winery • Khikhvi Classic',
    category: MenuCategory.WineClassicWhite,
    isWine: true,
    glassPrice: 17,
    bottlePrice: 75,
  },
  {
    id: 'wine_white_p_winery_kisi_classic',
    nameKa: 'პირველი მეღვინეობა • ქისი კლასიკი',
    nameEn: 'First Winery • Kisi Classic',
    category: MenuCategory.WineClassicWhite,
    isWine: true,
    glassPrice: 21,
    bottlePrice: 90,
  },
  {
    id: 'wine_white_me_wine_chardonnay_sb',
    nameKa: 'Me&Wine • Chardonnay Sauvignon Blanc (2022)',
    nameEn: 'Me&Wine • Chardonnay Sauvignon Blanc (2022)',
    category: MenuCategory.WineClassicWhite,
    isWine: true,
    glassPrice: 21,
    bottlePrice: 90,
  },
  {
    id: 'wine_white_chiora_tsolikouri',
    nameKa: 'Chiora • ლეჩხუმური ცოლიკოური (2023)',
    nameEn: 'Chiora • Lechkhumuri Tsolikouri (2023)',
    category: MenuCategory.WineClassicWhite,
    isWine: true,
    glassPrice: 19,
    bottlePrice: 84,
  },

  // --- QVEVRI & AMBER ---
  {
    id: 'wine_amber_damilie_goruli_chinuri',
    nameKa: 'Damilie • გორული მწვანე-ჩინური (2023)',
    nameEn: 'Damilie • Goruli Mtsvane-Chinuri (2023)',
    category: MenuCategory.WineQvevriAmber,
    isWine: true,
    glassPrice: 17,
    bottlePrice: 75,
  },
  {
    id: 'wine_amber_p_winery_kisi_qvevri',
    nameKa: 'პირველი მეღვინეობა • ქისი ქვევრი',
    nameEn: 'First Winery • Kisi Qvevri',
    category: MenuCategory.WineQvevriAmber,
    isWine: true,
    glassPrice: 19,
    bottlePrice: 84,
  },
  {
    id: 'wine_amber_p_winery_khikhvi_qvevri',
    nameKa: 'პირველი მეღვინეობა • ხიხვი ქვევრი',
    nameEn: 'First Winery • Khikhvi Qvevri',
    category: MenuCategory.WineQvevriAmber,
    isWine: true,
    glassPrice: 19,
    bottlePrice: 84,
  },
  {
    id: 'wine_amber_tevza_chinuri',
    nameKa: 'Tevza • ჩინური (2022)',
    nameEn: 'Tevza • Chinuri (2022)',
    category: MenuCategory.WineQvevriAmber,
    isWine: true,
    glassPrice: 18,
    bottlePrice: 78,
  },
  {
    id: 'wine_amber_chiche_4_decanters',
    nameKa: 'Chiche • 4 გრაფინი (ქისი, ხიხვი, მწვანე)',
    nameEn: 'Chiche • 4 Decanters (Kisi, Khikhvi, Mtsvane)',
    category: MenuCategory.WineQvevriAmber,
    isWine: true,
    glassPrice: 16,
    bottlePrice: 69,
  },

  // --- RED WINES ---
  {
    id: 'wine_red_chiche_saperavi',
    nameKa: 'Chiche • საფერავი (2022)',
    nameEn: 'Chiche • Saperavi (2022)',
    category: MenuCategory.WineRed,
    isWine: true,
    glassPrice: 17,
    bottlePrice: 75,
  },
  {
    id: 'wine_red_p_winery_saperavi_classic',
    nameKa: 'პირველი მეღვინეობა • საფერავი კლასიკი',
    nameEn: 'First Winery • Saperavi Classic',
    category: MenuCategory.WineRed,
    isWine: true,
    glassPrice: 15,
    bottlePrice: 66,
  },
  {
    id: 'wine_red_p_winery_saperavi_qvevri',
    nameKa: 'პირველი მეღვინეობა • საფერავი ქვევრი',
    nameEn: 'First Winery • Saperavi Qvevri',
    category: MenuCategory.WineRed,
    isWine: true,
    glassPrice: 21,
    bottlePrice: 90,
  },
  {
    id: 'wine_red_damilie_dzelshavi',
    nameKa: 'Damilie • ძელშავი (2024)',
    nameEn: 'Damilie • Dzelshavi (2024)',
    category: MenuCategory.WineRed,
    isWine: true,
    glassPrice: 20,
    bottlePrice: 87,
  },
  {
    id: 'wine_red_critera_primitivo',
    nameKa: 'Critera Primitivo (იტალია)',
    nameEn: 'Critera Primitivo (Italy)',
    category: MenuCategory.WineRed,
    isWine: true,
    glassPrice: 18,
    bottlePrice: 78,
  },
  {
    id: 'wine_red_corte_badin',
    nameKa: 'Corte Badin 1931 (იტალია)',
    nameEn: 'Corte Badin 1931 (Italy)',
    category: MenuCategory.WineRed,
    isWine: true,
    glassPrice: 16,
    bottlePrice: 72,
  },
  {
    id: 'wine_red_i_camponi_rosso',
    nameKa: 'I Camponi Rosso Veronese (2019)',
    nameEn: 'I Camponi Rosso Veronese (2019)',
    category: MenuCategory.WineRed,
    isWine: true,
    glassPrice: 16,
    bottlePrice: 72,
  },

  // --- SPARKLING & PET-NAT ---
  {
    id: 'wine_sparkling_prosecco_fili',
    nameKa: 'Prosecco Fili Extra Dry (იტალია)',
    nameEn: 'Prosecco Fili Extra Dry (Italy)',
    category: MenuCategory.WineSparklingPetNat,
    isWine: true,
    glassPrice: 21,
    bottlePrice: 90,
  },
  {
    id: 'wine_sparkling_mille_bolle_rose',
    nameKa: 'Mille Bolle Spumante Rosé Brut',
    nameEn: 'Mille Bolle Spumante Rosé Brut',
    category: MenuCategory.WineSparklingPetNat,
    isWine: true,
    glassPrice: 16,
    bottlePrice: 69,
  },
  {
    id: 'wine_sparkling_damilie_petnat_tsolikouri',
    nameKa: 'Damilie Pet-Nat • ცოლიკოური (2024)',
    nameEn: 'Damilie Pet-Nat • Tsolikouri (2024)',
    category: MenuCategory.WineSparklingPetNat,
    isWine: true,
    glassPrice: 19,
    bottlePrice: 81,
  },

  // --- ROSE ---
  {
    id: 'wine_rose_chiche_chard_sap',
    nameKa: 'Chiche • შარდონე საფერავი (2024)',
    nameEn: 'Chiche • Chardonnay Saperavi (2024)',
    category: MenuCategory.WineRose,
    isWine: true,
    glassPrice: 13,
    bottlePrice: 54,
  },
  {
    id: 'wine_rose_antieri_rose',
    nameKa: 'Antieri Rosé (იტალია)',
    nameEn: 'Antieri Rosé (Italy)',
    category: MenuCategory.WineRose,
    isWine: true,
    glassPrice: 25,
    bottlePrice: 108,
  },
];
